version: "3"

services:
  hello-world:
    build:
      context: .
      dockerfile: hello-world/Dockerfile
    ports:
      - 8080:8080
    environment:
      - GREETING=Hallo
    restart: on-failure
