version: "3"

services:
  hello-world:
    build:
      context: .
      dockerfile: hello-world/Dockerfile
    ports:
      - 8080:8080
    volumes: 
      - ./test/application-test.properties:/config/application.properties
    restart: on-failure
